//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class HelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("Helper");
		L.RegFunction("EditorMode", EditorMode);
		L.RegFunction("Platform", Platform);
		L.RegFunction("DecodeBase64", DecodeBase64);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EditorMode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = Helper.EditorMode();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Platform(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			string o = Helper.Platform();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DecodeBase64(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			string o = Helper.DecodeBase64(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

